answers: # to musi się zgadzać z "profile" w dbt_project.yml
  target: dev # domyślny target
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dbt-learning-472018 # <-- NAZWA Twojego projektu GCP
      dataset: dbt_test # <-- możesz zmienić np. na swoje imię/nick
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive

    production:
      type: bigquery
      method: oauth
      project: dbt-learning-472018 # <-- to samo tutaj
      dataset: dbt_production
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
